
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 20;
  public static final int READ = 9;
  public static final int OVER = 21;
  public static final int LT = 15;
  public static final int ELSE = 4;
  public static final int PLUS = 18;
  public static final int RPAREN = 23;
  public static final int THEN = 3;
  public static final int SEMI = 24;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int LPAREN = 22;
  public static final int GT = 16;
  public static final int WRITE = 10;
  public static final int ID = 11;
  public static final int NUM = 12;
  public static final int EOF = 0;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 13;
  public static final int EQ = 14;
  public static final int FOR = 8;
  public static final int REPEAT = 6;
  public static final int GET = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "FOR",
  "READ",
  "WRITE",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "GET",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI"
  };
}

